Compranator/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Compranator.Models
{
    public partial class ShoppingCart
    {
        CompranatorContexto db = new CompranatorContexto();
        string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CarritoId";

        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }

        // Método que simplifica la llamada de los carritos
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }
        public int AddToCart(Producto producto)
        {
            var cartItem = db.Carritos.SingleOrDefault(
                c => c.CarritoId == ShoppingCartId
                && c.ProductoCarritoFK == producto.ID);

            if (cartItem == null)
            {
                // Crea un nuevo carrito para el producto, si no existe
                cartItem = new Carrito
                {
                    ProductoCarritoFK = producto.ID,
                    CarritoId = ShoppingCartId,
                    cantidad = 1,
                    fecha_carrito = DateTime.Now
                };
                db.Carritos.Add(cartItem);
            }
            else
            {
                // Si existe un mismo producto en el carrito, 
                // incrementa la cantidad
                cartItem.cantidad++;
            }
            // Persistir en la BDD
            db.SaveChanges();
            return cartItem.cantidad;
        }

        public int RemoveFromCart(int id)
        {
            // Traer el carrito
            var cartItem = db.Carritos.Single(
                cart => cart.CarritoId == ShoppingCartId
                && cart.ID == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.cantidad > 1)
                {
                    cartItem.cantidad--;
                    itemCount = cartItem.cantidad;
                }
                else
                {
                    db.Carritos.Remove(cartItem);
                }
                // Persistir en la BDD
                db.SaveChanges();
            }
            return itemCount;
        }

        public void EmptyCart()
        {
            var cartItems = db.Carritos.Where(
                cart => cart.CarritoId == ShoppingCartId);

            foreach (var cartItem in cartItems)
            {
                db.Carritos.Remove(cartItem);
            }
            // Persistir en la BDD
            db.SaveChanges();
        }

        public List<Carrito> GetCartItems()
        {
            return db.Carritos.Where(
                cart => cart.CarritoId == ShoppingCartId).ToList();
        }

        public int GetCount()
        {
            // Obtener el recuento de cada artículo en el carro y sumarlos
            int? count = (from cartItems in db.Carritos
                          where cartItems.CarritoId == ShoppingCartId
                          select (int?)cartItems.cantidad).Sum();
            // Regreso 0 si todas las entradas son nulas
            return count ?? 0;
        }

        public decimal GetTotal()
        {
            // Multiply product price by count of that product to get 
            // the current price for each of those products in the cart
            // sum all product price totals to get the cart total
            decimal? total = (from cartItems in db.Carritos
                              where cartItems.CarritoId == ShoppingCartId
                              select (int?)cartItems.cantidad *
                              cartItems.ProductoCarrito.precio).Sum();

            return total ?? decimal.Zero;
        }

        public Pedido CreateOrder(Pedido pedido)
        {
            decimal orderTotal = 0;
            pedido.DetallesPedido = new List<Detalle>();

            var cartItems = GetCartItems();
            // Iterar sobre los elementos en la compra, 
            // añadiendo los detalles de la orden para cada
            foreach (var item in cartItems)
            {
                var orderDetail = new Detalle
                {
                    ProductoEnDetalleFK = item.ProductoCarritoFK,
                    PedidoEnDetalleFK = pedido.ID,
                    precio_unitario = item.ProductoCarrito.precio,
                    cantidad = item.cantidad
                };
                // Ajuste el total del pedido de la cesta de la compra
                orderTotal += (item.cantidad * item.ProductoCarrito.precio);
                pedido.DetallesPedido.Add(orderDetail);
                db.Detalles.Add(orderDetail);

            }
            // Ajuste total del fin de la cuenta OrderTotal
            pedido.total = orderTotal;

            // Persistir el pedido en la BDD
            db.SaveChanges();
            // Vaciar el carrito de la compra
            EmptyCart();
            // Retornar el ID del predido para confirmar la compra
            return pedido;
        }

        // We're using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] =
                        context.User.Identity.Name;
                }
                else
                {
                    // Generar un nuevo GUID al azar usando la clase System.Guid
                    Guid tempCartId = Guid.NewGuid();
                    // Enviar tempCartId nuevo a cliente como una cookie
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }
        // When a user has logged in, migrate their shopping cart to
        // be associated with their username
        public void MigrateCart(string userName)
        {
            var shoppingCart = db.Carritos.Where(
                c => c.CarritoId == ShoppingCartId);

            foreach (Carrito item in shoppingCart)
            {
                item.CarritoId = userName;
            }
            db.SaveChanges();
        }
    }
}

Compranator/Models/ShoppingCartViewModel.cs
using Compranator.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Compranator.Models
{
    public class ShoppingCartViewModel
    {
        public List<Carrito> ProductosEnCarrito { get; set; }
        public decimal total { get; set; }
    }

    public class ShoppingCartRemoveViewModel
    {
        public string mensaje { get; set; }
        public decimal total { get; set; }
        public int cartCount { get; set; }
        public int productoCount { get; set; }
        public int borrarId { get; set; }
    }
}

Compranator/Controllers/CheckoutController.cs
using Compranator.Helpers;
using Compranator.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Compranator.Controllers
{
    [Authorize(Roles = "Cliente")]
    public class CheckoutController : Controller
    {
        CompranatorContexto db = new CompranatorContexto();
        const string PromoCode = "FREE";
        //
        // GET: /Checkout/
        public ActionResult AddressAndPayment()
        {
            var currentUser = UsersHelpers.GetCurrentUser(this, db);
            var order = new Pedido();
            var cart = ShoppingCart.GetCart(this.HttpContext);
            order.total = cart.GetTotal();
            order.fecha_pedido = DateTime.Now;
            order.ClienteFK = currentUser.Id;

            return View(order);
        }

        //
        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var currentUser = UsersHelpers.GetCurrentUser(this, db);
            var order = new Pedido();
            TryUpdateModel(order);

            try
            {
                if (string.Equals(values["PromoCode"], PromoCode,
                    StringComparison.OrdinalIgnoreCase) == false)
                {
                    return View(order);
                }
                else
                {
                    order.Cliente.UserName = currentUser.UserName;//User.Identity.Name;
                    order.fecha_pedido = DateTime.Now;
                    order.ClienteFK = currentUser.Id;

                    // Guardar el pedido
                    db.Pedidos.Add(order);
                    db.SaveChanges();
                    // Procesar el pedido
                    var cart = ShoppingCart.GetCart(this.HttpContext);
                    cart.CreateOrder(order);

                    return RedirectToAction("Complete",
                        new { id = order.ID });
                }
            }
            catch
            {
                //Invalid - redisplay with errors
                return View(order);
            }
        }

        //
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            bool isValid = db.Pedidos.Any(
                o => o.ID == id &&
                o.Cliente.UserName == User.Identity.Name);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
	}
}

Compranator/Controllers/ShoppingCartController.cs
using Compranator.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Compranator.Controllers
{
    public class ShoppingCartController : Controller
    {
        CompranatorContexto db = new CompranatorContexto();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Mostrará el contenido del carrito a partir del ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                ProductosEnCarrito = cart.GetCartItems(),
                total = cart.GetTotal()
            };
            // Retorna a la vista del carrito - Index -
            return View(viewModel);
        }

        //
        // GET: /ShoppingCart/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Rocoge el producto de la BDD
            var agregarProducto = db.Productos
                .Single(prod => prod.ID == id);

            // Agrega el producto al carrito
            var cart = ShoppingCart.GetCart(this.HttpContext);

            int count = cart.AddToCart(agregarProducto);

            var resultado = new ShoppingCartRemoveViewModel
            {
                mensaje = Server.HtmlEncode(agregarProducto.modelo) +
                " ha sido agregado al carrito.",
                total = cart.GetTotal(),
                cartCount = cart.GetCount(),
                productoCount = count,
                borrarId = id
            };

            // Vuelve a los productos después de comprar
            //return Json(resultado);
            return RedirectToAction("Index");
           
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Recoge el producto para remover del carrito
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Recoge el nombre del producto para mostrarlo al comprar
            string nombreProducto = db.Carritos
                .Single(item => item.ID == id).ProductoCarrito.modelo;

            // Remueve un producto del carrito
            int itemCount = cart.RemoveFromCart(id);

            // Muestra un mensaje de confirmación
            var results = new ShoppingCartRemoveViewModel
            {
                mensaje = "Un (1)" + Server.HtmlEncode(nombreProducto) +
                    " se ha removido del carrito.",

                total = cart.GetTotal(),
                cartCount = cart.GetCount(),
                productoCount = itemCount,
                borrarId = id
            };
            return Json(results);
        }

        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["cartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }

        public void vaciarCarrito()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.EmptyCart();
        }
    }
    public class AllowJsonGetAttribute : ActionFilterAttribute
    {
        public override void OnResultExecuting(ResultExecutingContext filterContext)
        {
            var jsonResult = filterContext.Result as JsonResult;

            if (jsonResult == null)
                throw new ArgumentException("Action does not return a JsonResult, attribute AllowJsonGet is not allowed");

            jsonResult.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            base.OnResultExecuting(filterContext);
        }
    }
}

Compranator/Views/ShoppingCart/CartSummary.cshtml
@Html.ActionLink("Cart (" + ViewData["cartCount"] + ")",
    "Index",
    "ShoppingCart",
    new { id = "cart-status" })

Compranator/Views/ShoppingCart/Index.cshtml
@model Compranator.Models.ShoppingCartViewModel
@{
    ViewBag.Title = "Carrito de la compra";
}

<script type="text/javascript">
    $(function () {
        // Captura el clic de la rata, si existe la clase .RemoveLink
        $(".RemoveLink").click(function () {
            // Coge el producto a través del id
            var productoABorrar = $(this).attr("data-id");
            if (productoABorrar != '') {
                // Realiza el post vía ajax
                $.post("/ShoppingCart/RemoveFromCart", { "id": productoABorrar },
                    function (data) {
                        // Si todo va bien entra aquí y 
                        // Actualiza los productos del carrito
                        if (data.ItemCount == 0) {
                            $('#row-' + data.borrarId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.borrarId).text(data.productoCount);
                        }
                        $('#cart-total').text(data.total);
                        $('#update-message').text(data.mensaje);
                        $('#cart-status').text('Cart (' + data.cartCount + ')');
                    });
            }
        });
    });
</script>

<h3>
    <em>Productos</em> en carrito:
</h3>
<p class="button">
    @Html.ActionLink("Checkout >> ", "AddressAndPayment", "Checkout",
    routeValues: null, htmlAttributes: new { @class = "btn btn-primary btn-sm" })
</p>

<span class="label label-warning" id="update-message"></span>

@{
    if (Model.ProductosEnCarrito.Count > 0)
    {
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Producto</th>
                    <th></th>
                    <th>Precio (unidad)</th>
                    <th>Cantidad</th>
                </tr>
            </thead>
            <tbody>
                @{int num = 1;}
                @foreach (var item in Model.ProductosEnCarrito)
                {
                    if (num != 0) { 
                    <tr id="row-@item.ID">
                        <td>@num</td>
                        <td><img src="@Url.Content("~/Content/images/")@item.ProductoCarrito.url_image" alt="@item.ProductoCarrito.modelo" width="100" /></td>
                        <td>
                            @Html.ActionLink(item.ProductoCarrito.modelo, "Details", "Producto",
                        new
                        {
                            id = item.ProductoCarritoFK
                        }, null)
                        </td>
                        <td>
                            @item.ProductoCarrito.precio
                        </td>
                        <td id="item-count-@item.ID">
                            @item.cantidad
                        </td>
                        <td>
                            <a href="#" class="btn btn-primary btn-xs RemoveLink"
                               data-id="@item.ID">
                                <i class="glyphicon glyphicon-remove"></i>
                            </a>
                        </td>
                    </tr>
                    }
                    num++;
                }
            </tbody>
            <tfoot>
                <tr class="info">
                    <td><strong>Total</strong></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td id="cart-total"><strong>@Model.total</strong></td>
                </tr>
            </tfoot>
        </table>
    }
    else
    {
        <div>
            <p>
                No hay productos en el carrito actualmente, por favor comprame algo ;)
            </p>
        </div>
    }
}